#!/usr/bin/env bash
# generate-rofi-wallpaper.sh — generate blurred wallpaper + rofi current_wallpaper.rasi
# Usually called by set-wallpaper.sh; manual run also works (reads conf/config.sh SSOT).
# Blurred image: $HOME/wallpaper/blurred_wallpaper.png (single file, SSOT: conf/config.sh)
# Rasi shim: rofi/current_wallpaper.rasi next to font.rasi (SSOT: blurred_wallpaper)

set -e

# Source SSOT (shell: wallpaper_file -> wallpaper -> blurred_wallpaper)
# shellcheck source=/dev/null
source "$HOME/.config/hypr/conf/config.sh" 2>/dev/null || true

# Fallbacks if config.sh not yet stowed (default.jpg ships in wallpaper/ package)
wallpaper_file="${wallpaper_file:-default.jpg}"
wallpaper="${wallpaper:-$HOME/wallpaper/$wallpaper_file}"
blurred_wallpaper="${blurred_wallpaper:-$HOME/wallpaper/blurred_wallpaper.png}"

# Fall back to default.jpg when the configured file is missing
if [ ! -f "$wallpaper" ]; then
  echo "WARNING: wallpaper not found: $wallpaper, falling back to default.jpg" >&2
  wallpaper_file="default.jpg"
  wallpaper="$HOME/wallpaper/default.jpg"
fi

if [ ! -f "$wallpaper" ]; then
  echo "ERROR: even the fallback is missing: $wallpaper" >&2
  exit 1
fi

mkdir -p "$(dirname "$blurred_wallpaper")"

# Blur params — matches ML4W blur.sh: 50x30
blur="50x30"

# Prefer magick (ImageMagick 7), fall back to convert (IM6)
if command -v magick >/dev/null 2>&1; then
  magick "$wallpaper" -blur "$blur" "$blurred_wallpaper"
elif command -v convert >/dev/null 2>&1; then
  convert "$wallpaper" -blur "$blur" "$blurred_wallpaper"
else
  echo "ERROR: neither magick nor convert found (install imagemagick)" >&2
  exit 1
fi


echo "Wallpaper: $wallpaper"
echo "Blurred:   $blurred_wallpaper (blur $blur)"

# Rofi configs @import "current_wallpaper.rasi" -> mainbox background-image: @current-image
# Use relative path ../../wallpaper/blurred_wallpaper.png
# Write to the live path (works stowed or not); repo copy follows via your next commit.
live_rasi="$HOME/.config/rofi/current_wallpaper.rasi"
repo_rasi="$HOME/dotfiles/rofi/.config/rofi/current_wallpaper.rasi"

for rasi in "$live_rasi" "$repo_rasi"; do
  mkdir -p "$(dirname "$rasi")"
  printf '/* Generated by set-wallpaper.sh / generate-rofi-wallpaper.sh from hypr/conf/config.sh — do not edit manually */\n* { current-image: url("../../wallpaper/blurred_wallpaper.png", height); }\n' > "$rasi"
  echo "Generated: $rasi"
done
