# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = match:title ^Chromium$, tile on
windowrule = match:title ^pavucontrol$, float on
windowrule = match:title ^blueman-manager$, float on
windowrule = match:title ^nm-connection-editor$, float on
windowrule = match:title ^qalculate-gtk$, float on

# Browser Picture in Picture
windowrule = match:title ^Picture-in-Picture$, float on
windowrule = match:title ^Picture-in-Picture$, pin on
windowrule = match:title ^Picture-in-Picture$, move 69.5% 4%

# idleinhibit
windowrule = match:class ^.*$, idle_inhibit fullscreen

#xwayland related rules
# when moving objects in resolve a large border is produced 
# This rule prevents that and serves as a template for any problematic xwayland apps
windowrule = match:class ^resolve$ match:xwayland 1, no_blur on

# This is a general rule for xwayland apps but can have other consequences 
# for one user it impacted EMACs so it's disabled by default 
# It's here as a reference or for quick triage of xwayland ap
#windowrule = noblur, xwayland:1

